### PR TITLE
Added Word embeddings Solves issue #3 Add Word Embeddings

### LINKED ISSUE #3: Add Word Embeddings
**Name**
Word Embeddings (Word2Vec)

**Packages used**
tensorflow==2.5.0
numpy ==1.19.5
pandas==1.2.4

**Brief  explanation**
Word embedding is used to extract semantic relations between different words by plotting them in a vector space.

### PR DESCRIPTION
**Pull request by r-o-n-i-t**
Fixes #3 Add Word Embeddings

# Description

> This is a model for Word2Vec in Deep Learning.
> Word embedding is one of the most popular representations of document vocabulary. It can capture a word's context in a document, semantic and syntactic similarity, relation with other words, etc.
>Word2Vec is one of the most popular techniques to apply word embeddings using shallow neural networks.

## Type of change

- [x] New layer/algorithm

### Implementation details

> * Gensim == 3.6.0
> * Numpy == 1.19.5
> * Pandas == 1.2.4

## Tests

> The dataset used here is a subset of Amazon reviews from the Cell Phones & Accessories category. The data is stored as a JSON file and can be read using pandas.

Link to the Dataset: http://snap.stanford.edu/data/amazon/productGraph/categoryFiles/reviews_Cell_Phones_and_Accessories_5.json.gz

## Checklist

- [x] I have performed a self code_review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by mayureshagashe2105** [comment]
@r-o-n-i-t thank you for the PR. However, after carefully reviewing your PR, it has come to our attention that you have not followed the correct directory structure.
Your `Word2Vec.ipynb` file should be in the directory `DL_algorithms/Word2Vec` please make the appropriate changes and follow the folder structure mentioned in the issue and `contributing.md`
Thank you again, for your interest in ScratchAI

**Review by mayureshagashe2105 — CHANGES_REQUESTED** [review]
Please follow proper directory structure:
1. Create a directory named `Word2Vec` in [`DL_algorithms`](https://github.com/Math-behind-AI/ScratchAI/tree/main/DL_algorithms) folder and then add your [`Word2Vec.ipynb`](https://github.com/r-o-n-i-t/ScratchAI/blob/main/Word2Vec.ipynb) file into that folder. 
2. In short your `.ipynb` file should be in `DL_algorithms/Word2Vec/`
3. Please provide a neat readme file in the same directory.

**Comment by HemanthSai7** [comment]
@r-o-n-i-t thank you for the PR. We appreciate your work, but upon carefully reviewing your .ipynb notebook, It seems that you are using **gensim** library and calling **word2vec**. But instead, we have to implement the algorithms from scratch without using inbuilt functions. Just a suggestion, think of how will you develop word2vec if you were the developer developing it!

**Comment by r-o-n-i-t** [comment]
@mayureshagashe2105 @HemanthSai7 Thank you for your reviews.
I will keep the pointers in mind and resolve the issues asap.
Thank you.

**Comment by r-o-n-i-t** [comment]
@mayureshagashe2105 @HemanthSai7
I have updated it! Please review it.
Thank you.

**Pull request closed without merging**
