### PR TITLE
Mathematical formula for scoring added to Decision Tree

### LINKED ISSUE #28: Add a mathematical way to score results, rather than from direct libraries, in case of Decision Trees
**Is your feature request related to a problem? Please describe.**
Using libraries, defeats the main goal of this repository, that is creating everything from scratch. Using sklearn scoring model, defeats the purpose of this repo

**Describe the solution you'd like**
I'd like to create a function for calculating the R2score as well as accuracy, in Decision Tree

**Additional context**
Please assign me this issue under hacktoberfest

### PR DESCRIPTION
**Pull request by malay5**
fixes #28 

# Description

> :memo: Added the necessary functions in Decision Tree repo

## Type of change

Note: Please delete options that are not relevant.

- [*] New feature (non-breaking change which adds functionality)

## Checklist

- [*] I have performed a self code_review of my own code.

### CODE REVIEW

**Comment by malay5** [comment]
Please review this project based on Hacktoberfest 2022

**Comment by mayureshagashe2105** [comment]
Thank you for your PR! Your PR will be reviewed till tomorrow!

**Comment by malay5** [comment]
> Thank you for your PR! Your PR will be reviewed till tomorrow!

Could you pls. add this under hacktoberfest 2022

**Review by HemanthSai7 — APPROVED** [review]
Hey @malay5 , LGTM🚀.  Merging!

**Pull request merged**
