### PR TITLE
Added Principal Component Analysis Application

### PR DESCRIPTION
**Pull request by pps-19012**
Added Face Recognition using Principal Component Analysis through Eigenfaces. Will add more generalized version of the algorithm in future.

fixes #issue_number (if any, otherwise delete this line)

# Description
Application of PCA in Face Recognition.

> :memo: Please include a summary of the change. 
>  
> * Please also include relevant motivation and context.  
> * List any dependencies that are required for this change.  

## Type of change

Note: Please delete options that are not relevant.
- [ ] New layer/algorithm

### Implementation details
(only for `New layer/algorithm`)
> * List all the packages and their versions used.
numpy == 1.22.4
pandas == 1.4.2
matplotlib == 3.5.1
sklearn==0.20
> * Include test results such as:  
Obtained accuracy of 97.5% using AT&T database of faces.
>   * Implementation time for 1 instance of data.

## Tests

> :memo: Please describe the tests that you ran to verify your changes.
>  The instructions are present in the Readme Section of .ipynb file
> * Provide instructions so we can reproduce.  
Follow those instructions to get the outcome.
> * Please also list any relevant details for your test configuration.  

## Checklist

- [ ] I have performed a self code_review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by mayureshagashe2105** [comment]
@pps-19012 thank you for the PR. Your submission is still under review. All the maintainers are a bit swamped right now, your PR will be reviewed and merged by tomorrow. Thank you for your patience. Cheers!

**Comment by HemanthSai7** [comment]
Hi, @pps-19012 thank you for the PR. The Jupyter notebook is not able to load due to its file size (7Mb). Could you please try to reduce the size or check why the notebook has this size? 
Thanks

**Comment by pps-19012** [comment]
Yeah, sure. I will look into it and will inform you once I figure it out.

**Comment by pps-19012** [comment]
Please check now. I have updated the file.

**Review by HemanthSai7 — APPROVED** [review]
Looks good to me @pps-19012 .

**Pull request merged**
